version: "3"
services:
  web:
    build: .
    restart: on-failure
    env_file:
      - ./.env_dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./dj:/www/
      - /media/bk_images:/media/
    ports:
      - "80:8000"
    depends_on:
      - db
  db:
    image: "postgres:11.1-alpine"
    restart: unless-stopped
    env_file:
      - ./.env_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
