# Generated by Django 3.1.2 on 2020-10-10 04:33

import bk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('paragraph', models.CharField(max_length=5000)),
                ('image', models.FileField(upload_to=bk.models.image_path)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
